export const icon = {
  edit: 'pencil-outline',
  visibilityOn: 'eye-outline',
  visibilityOff: 'eye-off-outline',
  delete: 'delete-outline',
  close: 'close',
  skipNext: 'skip-next',
  skipPrevious: 'skip-previous',
  play: 'play-circle',
  pause: 'pause-circle',
  playlist: 'playlist-check',
  back: 'arrow-left',
  checkCircle: 'check-circle',
  restart: 'restart',
  copy: 'content-copy',
  empty: 'cancel',
  plus: 'plus',
  share: 'share-variant',
  list: 'format-list-bulleted',
  timer: 'timer-outline',
  image: 'image-outline',
  account: 'account-outline',
  settings: 'cog-outline',
  logout: 'logout',
}
